
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 23;
  public static final int READ = 14;
  public static final int OVER = 24;
  public static final int LT = 20;
  public static final int ELSE = 10;
  public static final int PLUS = 21;
  public static final int RPAREN = 26;
  public static final int THEN = 9;
  public static final int SEMI = 27;
  public static final int END = 11;
  public static final int IF = 8;
  public static final int LPAREN = 25;
  public static final int WRITE = 15;
  public static final int ID = 16;
  public static final int NUM = 17;
  public static final int DO = 6;
  public static final int BEGIN = 7;
  public static final int BOOLEAN = 3;
  public static final int EOF = 0;
  public static final int MINUS = 22;
  public static final int error = 1;
  public static final int EQ = 19;
  public static final int ASSIGN = 18;
  public static final int UNTIL = 13;
  public static final int INTEGER = 2;
  public static final int FOR = 4;
  public static final int TO = 5;
  public static final int REPEAT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "BOOLEAN",
  "FOR",
  "TO",
  "DO",
  "BEGIN",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "ID",
  "NUM",
  "ASSIGN",
  "EQ",
  "LT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LPAREN",
  "RPAREN",
  "SEMI"
  };
}

